services:
  mysql:
    image: mysql:8.0
    container_name: shipment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shipments
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:    
      - shipment-network

  api:
    build: .
    container_name: shipment-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:secret@mysql:3306/shipments
    ports:
      - "8000:8000"
    networks:         
      - shipment-network

volumes:
  mysql_data:

networks:              # 👈 agregado al final
  shipment-network:
    driver: bridge